[package]
name = "rflatten"
version = "0.2.1"
edition = "2024"
description = "Flatten subdirectories by moving all files to the root directory"
license = "GPL-3.0"

[dependencies]
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
tempfile = "3.10"
